### ISSUE TITLE
全角半角符号对应问题

### ISSUE THREAD

**Issue by zsxsoft** [laosb/halang#1]
半角符号：``[]`` ``{}`` ``()`` ``<>``

与以下全角符号如何一一对应：``〔〕`` ``〈〉`` ``《》`` ``「」`` ``『』`` ``【】`` ``＜＞`` ``｛｝`` ``（）`` ``〖〗`` ``≮≯`` ``≤≥`` ``∧∨``？

还有：``♂♀``

**Comment by laosb** [comment]
我的提案：

`〔〕` `【】` `〖〗` `【】` === `[]`

`「」` === `''`； `『』` === `""`

`《》`可以用于箭头函数中的`>`，但不用于大于、小于、大于等于、小于等于。

`〈〉`可以完全用于替换`<>`。

`{}` === `｛｝`

`（）` === `（）`

**Comment by zsxsoft** [comment]
问题来了，中文输入法下<>只能输入为《》

**Comment by laosb** [comment]
`大于`、`小于`、`大于等于`、`小于等于`可以成为运算符

**Comment by laosb** [comment]
`≤≥` 可以作为小于等于和大于等于，其他情况下不使用。

**Comment by zsxsoft** [comment]
``≥`` === ``>=`` === ``≮``
``≤`` === ``<=`` === ``≯``

This?

**Comment by laosb** [comment]
`≮≯`这两个不使用比较好，因为语义上不是很明确

**Comment by zsxsoft** [comment]
https://en.wiktionary.org/wiki/%E2%89%AE
(mathematics) not less than

**Comment by laosb** [comment]
嘛……也行

**Comment by zsxsoft** [comment]
那现在就是《》这俩了

**Comment by zsxsoft** [comment]
另外还有``——``和``-`` ``—`` ``－``的关系

**Comment by laosb** [comment]
破折号不使用就好了，连接号等同`-`

**Comment by zsxsoft** [comment]
我居然在想要不要支持``√`` === Math.sqrt……无视这条。

那《》的处理方式？

**Comment by zsxsoft** [comment]
刚才还发现这个``∥``是当``||``还是``//``……

https://en.wiktionary.org/wiki/%E2%88%A5
``
(geometry) Parallel lines.

{\displaystyle AB\parallel CD} {\displaystyle AB\parallel CD} indicates that line AB is parallel to line CD
See ‖ for other uses of double vertical lines, also called a caesura.
``

**Comment by laosb** [comment]
要不要halang完全支持latext😆这些搞个polyfill就好了，我觉得。

这个，拟像就好了，当成单行注释。

**Comment by zsxsoft** [comment]
这样的话还要支持从∑求和开始到∫求积分……口胡（

所以言归正传，《》的处理方式？

**Comment by laosb** [comment]
我认为上面的方式可以

**Comment by zsxsoft** [comment]
主要的麻烦是，如果《》不能替代<>的话，中文输入法下要打<>就不方便了

**Comment by laosb** [comment]
`大于` `小于`作为关键字去用……我觉得直接作为大小于，语义上讲不通……

**Comment by laosb** [comment]
似乎很多人都支持直接替代……突然觉得也是可以接受的

**Comment by laosb** [comment]
不过应用时我还是推荐用中文关键字

**Comment by laosb** [comment]
@zsxsoft is that ok to you?

**Comment by zsxsoft** [comment]
中文关键字……你指  ``如果 （1大于2） `` 这样？

**Comment by laosb** [comment]
true

**Comment by zsxsoft** [comment]
感觉还是《》好些啊……反正这些符号本来也脱离人的本意了

**Comment by laosb** [comment]
@zsxsoft 照顾一下我这种洁癖吧……都实现一下？

**Comment by zsxsoft** [comment]
这种要两个字符以上的滞后实现吧，优先实现单字符的

**Comment by laosb** [comment]
嗯

**Comment by laosb** [comment]
我下次把这个整理到definition里去，closing
