### ISSUE TITLE
关于“≮”及“≯”的问题

### ISSUE THREAD

**Issue by HolyYea** [laosb/halang#2]
我认为“不小于”与“不大于”符号应该抛弃，因为它不符合我们通常的思维方式，并且在与“大于等于”、“小于等于”混用时不便于阅读。

**Comment by laosb** [comment]
我有想到过，但是不这么想的人应该也不会去用……@zsxsoft

**Comment by zsxsoft** [comment]
@laosb 我就是输入法按v1看符号的（

**Comment by HolyYea** [comment]
我觉得`「」`也不常用，但是十分形象。

**Comment by laosb** [comment]
@HolyYea 这是台湾标准里的引号，建议使用这个而不是弯引号。

**Comment by HolyYea** [comment]
@laosb 在香港标准里，应该是先用单引号，再套双引号，这个冲突呢？

**Comment by laosb** [comment]
这不冲突。按照definition分别对应到了单引号和双引号上，怎么用就是个人喜好问题了。
